name: Autobuild Plugins

# Controls when the action will run.
on:
  push:
    paths:
      - '*/src/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: compile plugins
    runs-on: ubuntu-latest

    steps:
      - name: clean working directory
        run: |
          rm -rf /home/runner/work/${{ github.repository }}

      - name: checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: detect changed files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: build plugins
        run: node .github/workflows/run-bdbuilder ${{ steps.files.outputs.all }}

      - name: stage build
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: .
          retention-days: 1

  publish:
    name: publish
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: use build
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: .

      - name: commit build
        run: |
          git add -a
          git config --local user.email "actions@github.com"
          git config --local user.name "PluginBuilder"
          git commit -m "[CI Chore] Compile plugin(s)" || true

      - name: Push build commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
